image:
  - Visual Studio 2017

install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET SBT_HOME=C:\sbt\bin
  - cmd: SET PATH=%SBT_HOME%;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g

before_build:
  - ps: >-
      $buildId = $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, '0');
      $versionSuffixPR = "-PR$($env:APPVEYOR_PULL_REQUEST_NUMBER)-$buildId";
      $branchName = "$env:APPVEYOR_REPO_BRANCH".Replace("_","");
      $versionSuffixBRANCH = "-$branchName-$buildId";
      $env:VersionSuffix = if ("$env:APPVEYOR_REPO_TAG" -eq "true") { "" } else { if ("$env:APPVEYOR_PULL_REQUEST_NUMBER") { $versionSuffixPR } else { $versionSuffixBRANCH } };

build_script:
  - cmd: echo vs %VersionSuffix%"
  - cmd: dotnet pack build.proj -v n
  - cmd: dotnet test build.proj -v n

artifacts:
  - path: artifact\nupkg\*.nupkg
    name: nupkgs
    type: NuGetPackage

on_finish:
  - ps: >-
      $testResults = @(
         '.\artifact\test_results\TestResults.xml'
      );
      Foreach ($path in $testResults) {
        If (Test-Path $path) {
          (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path $path));
        }
      }

cache:
  - C:\sbt\
